language: bash
sudo: true

addons:
  apt:
    packages:
    - dhcpd

install: git clone https://github.com/Freifunk-Troisdorf/static-dhcp

script: /usr/sbin/dhcpd -t -cf ./static-dhcp/dhcpd.conf
