language: bash
sudo: true

addons:
  apt:
    packages:
    - isc-dhcp-server

install: git clone https://github.com/Freifunk-Troisdorf/static-dhcp

script: /etc/init.d/isc-dhcp-server start
